/**
 * ZeroDaily Core TypeScript Definitions
 * Aligned strictly with the FastAPI Backend (Docs.md) and FCM Notification Architecture (notification-arch.md).
 */

/** Supported tech category keys */
export type CategoryKey =
  | 'all'
  | 'cybersec'
  | 'ai'
  | 'programming'
  | 'robotics'
  | 'defense_aerospace'
  | 'hardware'
  | 'finance';

/** Category metadata structure matching GET /api/v1/categories */
export interface CategoryMeta {
  key: CategoryKey;
  name: string;
  description: string;
  badgeColor: string;
  accentColor: string;
  fcmTopic: string;
  fallbackImage: string;
  fallbackImages: string[];
}

/** Article schema matching DynamoDB zerodaily-articles and API response */
export interface Article {
  /** Canonical source article URL (unique identifier) */
  id: string;
  /** Category taxonomy key */
  category: CategoryKey;
  /** Original source headline */
  title?: string;
  /** Satirical roasted headline generated by Bedrock DeepSeek */
  heading: string;
  /** High-impact punchy short summary (60 words format) */
  shortSummary: string;
  /** Full analytical and satirical breakdown (multi-paragraph) */
  fullSummary: string;
  /** ISO-8601 UTC timestamp of original publication */
  published_at: string;
  /** Link to original publisher article */
  link: string;
  /** Cloudflare CDN URL to optimized 800px WebP image */
  image_url: string;
  /** Whether the article qualified for breaking push notifications */
  is_breaking?: boolean;
  /** Alert punchline (max 50 chars) sent via FCM */
  push_punchline?: string;
}

/** Cursor-based pagination metadata returned by GET /api/v1/feed */
export interface PaginationMeta {
  has_more: boolean;
  next_cursor: string | null;
  count: number;
}

/** API feed response envelope */
export interface FeedResponse {
  status: 'success' | 'error';
  category?: string;
  data: Article[];
  pagination: PaginationMeta;
}

/** Single article lookup response envelope */
export interface SingleArticleResponse {
  status: 'success' | 'error';
  data: Article;
  message?: string;
}

/** Notification history item matching GET /api/v1/notifications/history */
export interface NotificationItem {
  article_id: string;
  category: CategoryKey;
  heading: string;
  push_punchline: string;
  image_url: string;
  published_at: string;
}

/** Notification history API response envelope */
export interface NotificationHistoryResponse {
  status: 'success' | 'error';
  data: NotificationItem[];
  count: number;
}

/** Incoming FCM push notification data payload */
export interface FCMDataPayload {
  article_id: string;
  category: string;
  image_url: string;
  click_action?: string;
}

/** User push notification category preferences */
export type NotificationPreferences = Record<CategoryKey, boolean> & {
  breaking_all: boolean;
};

/** User account profile stored in DynamoDB and returned by API */
export interface UserProfile {
  user_id: string;
  email?: string | null;
  display_name?: string | null;
  avatar_url?: string | null;
  is_anonymous: boolean;
  created_at: string;
  last_active_at: string;
  topic_preferences: Record<string, boolean>;
  algo_weights: Record<string, number>;
  bookmarked_articles: string[];
  reading_count: number;
  is_pending_deletion?: boolean;
  deletion_scheduled_at?: string | null;
  account_restored?: boolean;
}

/** Account deletion response envelope */
export interface AccountDeletionResult {
  status: 'success' | 'error';
  message: string;
  deletion_scheduled_at?: string;
  is_pending_deletion?: boolean;
}

/** Authentication response envelope */
export interface AuthResponse {
  status: 'success' | 'error';
  access_token: string;
  token_type: string;
  user: UserProfile;
  message?: string;
}

/** User interaction tracking event payload */
export interface TrackingEventPayload {
  article_id: string;
  category: string;
  action: 'read' | 'dwell' | 'skip' | 'bookmark' | 'share' | 'full_roast';
  duration_seconds?: number;
}

/** Tracking response envelope */
export interface TrackingResponse {
  status: 'success' | 'error';
  user_id: string;
  action: string;
  algo_weights: Record<string, number>;
}

/** Bookmark sync response envelope */
export interface SyncBookmarksResponse {
  status: 'success' | 'error';
  bookmarks: string[];
}
