/**
 * ZeroDaily Core TypeScript Definitions
 * Aligned strictly with the FastAPI Backend (Docs.md) and FCM Notification Architecture (notification-arch.md).
 */

/** Supported tech category keys */
export type CategoryKey =
  | 'all'
  | 'cybersec'
  | 'ai'
  | 'programming'
  | 'robotics'
  | 'defense_aerospace'
  | 'hardware'
  | 'finance';

/** Category metadata structure matching GET /api/v1/categories */
export interface CategoryMeta {
  key: CategoryKey;
  name: string;
  description: string;
  badgeColor: string;
  accentColor: string;
  fcmTopic: string;
  fallbackImage: string;
  fallbackImages: string[];
}

/** Article schema matching DynamoDB zerodaily-articles and API response */
export interface Article {
  /** Canonical source article URL (unique identifier) */
  id: string;
  /** Category taxonomy key */
  category: CategoryKey;
  /** Original source headline */
  title?: string;
  /** Satirical roasted headline generated by Bedrock DeepSeek */
  heading: string;
  /** High-impact punchy short summary (60 words format) */
  shortSummary: string;
  /** Full analytical and satirical breakdown (multi-paragraph) */
  fullSummary: string;
  /** ISO-8601 UTC timestamp of original publication */
  published_at: string;
  /** Link to original publisher article */
  link: string;
  /** Cloudflare CDN URL to optimized 800px WebP image */
  image_url: string;
  /** Whether the article qualified for breaking push notifications */
  is_breaking?: boolean;
  /** Alert punchline (max 50 chars) sent via FCM */
  push_punchline?: string;
}

/** Cursor-based pagination metadata returned by GET /api/v1/feed */
export interface PaginationMeta {
  has_more: boolean;
  next_cursor: string | null;
  count: number;
}

/** API feed response envelope */
export interface FeedResponse {
  status: 'success' | 'error';
  category?: string;
  data: Article[];
  pagination: PaginationMeta;
}

/** Single article lookup response envelope */
export interface SingleArticleResponse {
  status: 'success' | 'error';
  data: Article;
  message?: string;
}

/** Notification history item matching GET /api/v1/notifications/history */
export interface NotificationItem {
  article_id: string;
  category: CategoryKey;
  heading: string;
  push_punchline: string;
  image_url: string;
  published_at: string;
}

/** Notification history API response envelope */
export interface NotificationHistoryResponse {
  status: 'success' | 'error';
  data: NotificationItem[];
  count: number;
}

/** Incoming FCM push notification data payload */
export interface FCMDataPayload {
  article_id: string;
  category: string;
  image_url: string;
  click_action?: string;
}

/** User push notification category preferences */
export type NotificationPreferences = Record<CategoryKey, boolean> & {
  breaking_all: boolean;
};
