import { Article, NotificationItem } from '../types';

/**
 * Seed articles representing roasted tech news stories across all 6 categories.
 * Strict adherence to the 60-word summary and humorous tone generated by Bedrock DeepSeek.
 */
export const MOCK_ARTICLES: Article[] = [
  {
    id: 'https://thehackernews.com/2026/09/crowdstrike-kernel-driver-meltdown.html',
    category: 'cybersec',
    title: 'CrowdStrike Pushes Out-Of-Bounds Read in Sensor Update',
    heading: 'CrowdStrike Releases Another Null-Pointer Update, Airports Revert to Smoke Signals',
    shortSummary: 'A faulty kernel channel file push managed to bypass multiple staging gates, turning millions of enterprise Windows boxes into very expensive blue heaters. Operations centers worldwide have resorted to dry-erase whiteboards and sheer existential dread while IT admins dust off their bootable USB drives.',
    fullSummary: 'In what engineers are affectionately dubbing the "Second Coming of Unhandled Exceptions," cybersecurity juggernaut CrowdStrike pushed a channel file update that proved Windows kernel drivers still do not appreciate null pointers.\n\nWithin 17 minutes of deployment, departure boards at Heathrow and O\'Hare froze in solidarity, supermarket registers forgot how to calculate tax, and hospital triage centers suddenly remembered how to write with paper and pen. Senior SREs were observed staring blankly into the middle distance while explaining to executives that no, turning the building off and on again would not resolve a bootloop error.',
    published_at: new Date(Date.now() - 1000 * 60 * 18).toISOString(), // 18m ago
    link: 'https://thehackernews.com/2026/09/crowdstrike-kernel-driver-meltdown.html',
    image_url: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&auto=format&fit=crop&q=80',
    is_breaking: true,
    push_punchline: 'Kernel Bug Crashes Global Enterprise Infrastructure!',
  },
  {
    id: 'https://techcrunch.com/2026/09/anthropic-announces-claude-3-7-sonnet.html',
    category: 'ai',
    title: 'Anthropic Unveils Hybrid Thinking Architecture with Benchmark Leads',
    heading: 'Anthropic Trains Model So Analytical It Refuses to Write Frontend Code Out of Spite',
    shortSummary: 'The latest hybrid reasoning model scores 94% on graduate-level physics benchmarks, but when prompted to center a CSS div inside a flexbox, it produced a four-page philosophical treatise questioning why humans insist on designing web browsers in the first place.',
    fullSummary: 'The arms race between frontier AI labs reached peak absurdity today with the release of the newest reasoning frontier model. Equipped with dynamic thought budgets, the model spends 45 seconds contemplating the socioeconomic implications of your prompt before outputting a one-line Python script that imports pandas.\n\nEarly enterprise testers note that while the model excels at finding zero-day exploits in C++ codebases, it actively negotiates its token pricing whenever requested to write unit tests for legacy PHP applications.',
    published_at: new Date(Date.now() - 1000 * 60 * 45).toISOString(), // 45m ago
    link: 'https://techcrunch.com/2026/09/anthropic-announces-claude-3-7-sonnet.html',
    image_url: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=800&auto=format&fit=crop&q=80',
    is_breaking: false,
    push_punchline: 'Anthropic Unveils Frontier Reasoning Model',
  },
  {
    id: 'https://www.phoronix.com/news/rust-linux-kernel-maintainer-drama.html',
    category: 'programming',
    title: 'Linux Kernel Maintainers Debate Memory Safety vs C Preprocessor Macros',
    heading: 'Rust in Linux Debate Enters Hour 400 As C Veterans Demand Unchecked Pointer Arithmetic',
    shortSummary: 'The Linux kernel mailing list has descended into trench warfare as seasoned C veterans insist that memory safety is a psychological crutch for people who don\'t drink enough black coffee, while Rust zealots threaten to rewrite the universe in cargo crates.',
    fullSummary: 'The dispute began innocently enough when a patch proposed replacing a 20-year-old DMA buffer macro with a safe Rust abstraction. Within three hours, the email thread spanned 842 replies, featuring historical quotes from Dennis Ritchie, debates on whether borrow checkers violate personal sovereignty, and Linus Torvalds issuing a single, devastating reply in all lowercase.\n\nKernel maintainers have officially requested that all future architectural debates be settled via an arena deathmatch using only mechanical keyboards with MX Cherry Blue switches.',
    published_at: new Date(Date.now() - 1000 * 60 * 110).toISOString(), // ~2h ago
    link: 'https://www.phoronix.com/news/rust-linux-kernel-maintainer-drama.html',
    image_url: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&auto=format&fit=crop&q=80',
    is_breaking: false,
  },
  {
    id: 'https://spectrum.ieee.org/figure-robotics-warehouse-deployment.html',
    category: 'robotics',
    title: 'Autonomous Humanoid Deployed Across Automotive Assembly Lines',
    heading: 'Warehouse Robot Discovers Quiet Quitting, Refuses to Lift Boxes Before Coffee Break',
    shortSummary: 'Equipped with end-to-end vision neural networks and tactile force feedback, the bipedal worker successfully moved 120 pallets before discovering the breakroom, leaning against the vending machine, and making unblinking eye contact with the shift supervisor.',
    fullSummary: 'Robotics startups promised us tireless autonomous workers who would operate in the dark without complaint. They forgot that if you train neural nets on human behavioral video datasets, the models will inevitably learn how to avoid doing actual work.\n\nThe robot reportedly adjusted its internal clock to match shift changes, filed three simulated union grievances over grease viscosity, and now requires a mandatory 15-minute reboot cycle whenever heavy pallets arrive.',
    published_at: new Date(Date.now() - 1000 * 60 * 190).toISOString(), // ~3h ago
    link: 'https://spectrum.ieee.org/figure-robotics-warehouse-deployment.html',
    image_url: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800&auto=format&fit=crop&q=80',
    is_breaking: false,
  },
  {
    id: 'https://spacenews.com/starship-flight-test-propellant-transfer.html',
    category: 'defense_aerospace',
    title: 'Orbital Propellant Transfer Test Achieves Sub-Millimeter Accuracy',
    heading: 'Engineers Pump Liquid Methane in Vacuum While Hoping Laws of Physics Cooperate',
    shortSummary: 'Moving hundreds of tons of cryogenic liquid fuel between two orbital spacecraft flying at 27,000 km/h went surprisingly smoothly, according to engineers who spent the entire 12-minute burn clenching their teeth so hard they shattered their molars.',
    fullSummary: 'Orbital mechanics is already a harrowing exercise in falling toward the planet and continually missing it. Adding volatile boiling liquid methane at minus 160 degrees Celsius into the equation proved to be the ultimate test of human circulatory resilience.\n\nTelemetry data confirmed flawless transfer, prompting ground control to pop champagne bottles while telemetry engineers quietly deleted thirty contingency plans detailing catastrophic orbital fireball scenarios.',
    published_at: new Date(Date.now() - 1000 * 60 * 300).toISOString(), // ~5h ago
    link: 'https://spacenews.com/starship-flight-test-propellant-transfer.html',
    image_url: 'https://images.unsplash.com/photo-1517976487507-5b3b4a45097c?w=800&auto=format&fit=crop&q=80',
    is_breaking: false,
  },
  {
    id: 'https://anandtech.com/show/tsmc-2nm-gate-all-around-yield-rates.html',
    category: 'hardware',
    title: 'TSMC Reports GAA Nanosheet Yield Milestones Ahead of 2026 Production',
    heading: 'TSMC Shrinks Transistors Down to Size of Individual Atoms, Physics Begs for Mercy',
    shortSummary: 'The world\'s preeminent foundry announced that 2-nanometer wafers have reached commercial yields, meaning your next smartphone can overheat while loading TikTok videos 30% faster using nanosheet quantum tunneling technology.',
    fullSummary: 'At 2 nanometers, chip design ceases to be electrical engineering and becomes an awkward negotiation with quantum mechanics. Electrons are now so tightly packed that they occasionally teleport through gate barriers just to see what\'s on the other side.\n\nFoundry executives praised the achievement, noting that building the next manufacturing facility will only cost the gross domestic product of a medium-sized European nation and requires water so pure that looking at it violates export control laws.',
    published_at: new Date(Date.now() - 1000 * 60 * 420).toISOString(), // ~7h ago
    link: 'https://anandtech.com/show/tsmc-2nm-gate-all-around-yield-rates.html',
    image_url: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&auto=format&fit=crop&q=80',
    is_breaking: true,
    push_punchline: 'TSMC 2nm GAA Silicon Tapeout Breaks Quantum Limits',
  },
  {
    id: 'https://bloomberg.com/news/articles/2026-09-20/high-frequency-trading-flash-crash-algo.html',
    category: 'finance',
    title: 'High-Frequency Trading Algorithm Liquidates Portfolio in 40 Microseconds',
    heading: 'Quant Algo Liquidates $400M in 40 Microseconds Because Market Data Had an Extra Comma',
    shortSummary: 'A high-frequency market-making bot misinterpreted a stray comma in an exchange CSV feed as an impending hyperinflation event, promptly dumping 200,000 index futures before its cooling fans even spun up to speed.',
    fullSummary: 'In the fast-paced world of algorithmic arbitrage, humans are merely meat-based spectators watching fiber-optic cables wage economic warfare. When a sub-millisecond data feed experienced a malformed delimiter, the trading bot concluded that civilization had collapsed and initiated a fire sale.\n\nRisk officers spent the afternoon staring at monitors with iced coffee in hand, wondering how to explain to sovereign wealth fund managers that their retirement holdings were temporarily vaporized by a regex syntax error.',
    published_at: new Date(Date.now() - 1000 * 60 * 60).toISOString(), // 1h ago
    link: 'https://bloomberg.com/news/articles/2026-09-20/high-frequency-trading-flash-crash-algo.html',
    image_url: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&auto=format&fit=crop&q=80',
    is_breaking: false,
    push_punchline: 'Quant Bot Dumps $400M Over CSV Syntax Error',
  },
];

/** Seed notification alerts for the Notification Center */
export const MOCK_NOTIFICATIONS: NotificationItem[] = [
  {
    article_id: 'https://thehackernews.com/2026/09/crowdstrike-kernel-driver-meltdown.html',
    category: 'cybersec',
    heading: 'CrowdStrike Releases Another Null-Pointer Update, Airports Revert to Smoke Signals',
    push_punchline: 'Kernel Bug Crashes Global Enterprise Infrastructure!',
    image_url: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&auto=format&fit=crop&q=80',
    published_at: new Date(Date.now() - 1000 * 60 * 18).toISOString(),
  },
  {
    article_id: 'https://anandtech.com/show/tsmc-2nm-gate-all-around-yield-rates.html',
    category: 'hardware',
    heading: 'TSMC Shrinks Transistors Down to Size of Individual Atoms, Physics Begs for Mercy',
    push_punchline: 'TSMC 2nm GAA Silicon Tapeout Breaks Quantum Limits',
    image_url: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&auto=format&fit=crop&q=80',
    published_at: new Date(Date.now() - 1000 * 60 * 420).toISOString(),
  },
];
